FIXUP: BACKPORT: UPSTREAM: KVM: x86: Use __try_cmpxchg_user() to emulate atomic accesses
0-day errors:

>> arch/x86/include/asm/uaccess.h:494:22: error: expected ':'
   or ')' before '_ASM_EXTABLE_TYPE_REG'
     494 |  _ASM_EXTABLE_TYPE_REG(1b, 2b, EX_TYPE_EFAULT_REG,  \
         |  ^~~~~~~~~~~~~~~~~~~~~

The compilation error occurs because macro '_ASM_EXTABLE_TYPE_REG' is
undefined. Pick the definiton of this macro from upstream (commit
4b5305decc84).

BUG=b:242657184,b:227610040
TEST=POC

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: Ieb82ab31b45acbb4a2000f722f6526828a9d4e22
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3834227
Reviewed-by: Guenter Roeck <groeck@chromium.org>