BACKPORT: r8152: redefine REALTEK_USB_DEVICE macro
Redefine REALTEK_USB_DEVICE macro with USB_DEVICE_INTERFACE_CLASS and
USB_DEVICE_AND_INTERFACE_INFO to simply the code.

Although checkpatch.pl shows the following error, it is more readable.

	ERROR: Macros with complex values should be enclosed in parentheses

Signed-off-by: Hayes Wang <hayeswang@realtek.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 55319eeb5bbcd3c73366de92ff224bd62325a68d)

BUG=b:202907799, b:300677194
TEST=Future patches easier to pick

Conflicts:
  drivers/net/usb/r8152.c
...we had conflicts because we had the version of commit 1bd3a383075c
("r8152: add PID for the Lenovo OneLink+ Dock") that came through
linux-stable. To get this backport, I reverted the version that came
from stable, cleanly picked this patch, and then clealy picked commit
1bd3a383075c. ...then squashed the result.

Change-Id: I8ae2e71905c5ac48bf2f72189a1176f5547824a0
Signed-off-by: Douglas Anderson <dianders@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4967954
Reviewed-by: Grant Grundler <grundler@chromium.org>