Revert "UPSTREAM: KVM: x86: fix typo in __try_cmpxchg_user causing non-atomicness"
This reverts commit fbb0047dc0c3328940e09acfaec3a8789054f2e5.

Reason for revert: Fix build error:
ld: arch/x86/kvm/x86.o:(__ex_table+0xb0): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xbc): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xc8): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xd4): undefined reference to
`EX_TYPE_EFAULT_REG'

BUG=b:242431919
TEST=CQ

Change-Id: Ic8185656ededb9d94553ace2f3c6c7527afb70e8
Signed-off-by: Zubin Mithra <zsm@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4383513
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Zubin Mithra <zsm@chromium.org>
Tested-by: Zubin Mithra <zsm@chromium.org>