Revert "BACKPORT: KVM: x86: Use __try_cmpxchg_user() to emulate atomic accesses"
This reverts commit 2ea5ade821121dce7abae1aaba92ae84bcdef913.

Reason for revert: Fix build error:
ld: arch/x86/kvm/x86.o:(__ex_table+0xb0): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xbc): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xc8): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xd4): undefined reference to
`EX_TYPE_EFAULT_REG'

BUG=b:242431919
TEST=CQ

Change-Id: I400bd7e19392b094555c63885e0d13ad2e598163
Signed-off-by: Zubin Mithra <zsm@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4383514
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Tested-by: Zubin Mithra <zsm@chromium.org>
Commit-Queue: Zubin Mithra <zsm@chromium.org>